# Generated by Django 3.2.15 on 2022-11-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shard',
            field=models.CharField(blank=True, choices=[('shard_1', 'shard_1'), ('shard_2', 'shard_2'), ('shard_3', 'shard_3')], max_length=120, null=True),
        ),
    ]
