# Generated by Django 3.2.15 on 2022-11-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_user_shard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
