# Generated by Django 3.2.15 on 2022-11-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_user_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zone',
            field=models.CharField(blank=True, choices=[('zone_1', 'Zona 1'), ('zone_2', 'Zona 2'), ('zone_3', 'Zona 3')], default='zone_1', max_length=120, null=True),
        ),
    ]
